- name: Increase number of watches
  ansible.builtin.lineinfile:
    line: fs.inotify.max_user_watches=204800
    path: /etc/sysctl.conf
  become: true

- name: Copy config
  ansible.builtin.copy:
    src: files/syncthing
    dest: "/home/{{ ansible_user }}/.config"
    mode: "0700"
    backup: true

- name: Add PGP keys
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Add stable channel to APT sources
  ansible.builtin.lineinfile:
    line: deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
    path: /etc/apt/sources.list.d/syncthing.list
    mode: "0644"
    create: true
  become: true

- name: Set priority
  ansible.builtin.blockinfile:
    block: |
      Package: *
      Pin: origin apt.syncthing.net
      Pin-Priority: 990
    path: /etc/apt/preferences.d/syncthing
    create: true
    mode: "0644"
  become: true

- name: Install syncthing
  ansible.builtin.apt:
    pkg: syncthing
    state: present
    update_cache: true
  become: true

- name: Start service
  ansible.builtin.systemd:
    name: syncthing@pi
    enabled: true
    state: started
  become: true
