- name: Copy script file
  ansible.builtin.template:
    src: templates/backup.sh.j2
    dest: /home/{{ ansible_user }}/backup.sh
    mode: "0500"
  register: backup_script

- name: Copy backup service file
  ansible.builtin.template:
    src: templates/backup.service.j2
    dest: /etc/systemd/system/backup.service
    mode: "0644"
  become: true

- name: Copy integrity service file
  ansible.builtin.template:
    src: templates/integrity.service.j2
    dest: /etc/systemd/system/integrity.service
    mode: "0644"
  become: true

- name: Copy timer file
  ansible.builtin.copy:
    src: files/backup.timer
    dest: /etc/systemd/system/backup.timer
    mode: "0644"
  become: true

- name: Enable backup service
  ansible.builtin.systemd:
    name: backup.service
    enabled: true
    daemon_reload: true
  become: true

- name: Enable integrity service
  ansible.builtin.systemd:
    name: integrity.service
    enabled: true
    daemon_reload: true
  become: true

- name: Enable timer
  ansible.builtin.systemd:
    name: backup.timer
    state: started
    enabled: true
  become: true
