- name: Copy script file
  ansible.builtin.template:
    src: templates/backup.sh.j2
    dest: /home/{{ ansible_user }}/backup.sh
    mode: "0500"
  register: backup_script

- name: Copy service files
  ansible.builtin.template:
    src: "templates/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: "0644"
  become: true
  loop:
    - backup
    - integrity

- name: Copy timer files
  ansible.builtin.copy:
    src: "files/{{ item }}.timer"
    dest: "/etc/systemd/system/{{ item }}.timer"
    mode: "0644"
  become: true
  loop:
    - backup
    - integrity

- name: Enable services
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    enabled: true
    daemon_reload: true
  become: true
  loop:
    - backup
    - integrity

- name: Enable timers
  ansible.builtin.systemd:
    name: "{{ item }}.timer"
    state: started
    enabled: true
  become: true
  loop:
    - backup
    - integrity
