- name: Setup logging
  hosts: all
  vars:
    config_dir: /home/{{ ansible_user }}/.config/matrix-commander
    store_dir: /home/{{ ansible_user }}/.local/share/matrix-commander/store
  vars_prompt:
    - name: matrix_server
      prompt: Matrix server
      private: false
    - name: matrix_user
      prompt: Matrix user
      private: false
    - name: matrix_password
      prompt: Matrix password
      private: true

  tasks:
    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
      become: true

    - name: Install matrix-commander
      ansible.builtin.pip:
        name: matrix-commander
        extra_args: --user

    - name: Create config dir
      ansible.builtin.file:
        path: "{{ config_dir }}"
        state: directory
        mode: "0700"

    - name: Setup matrix account
      ansible.builtin.command:
        cmd: >
          /home/{{ ansible_user }}/.local/bin/matrix-commander --login PASSWORD
          --homeserver {{ matrix_server }}
          --user-login {{ matrix_user }}
          --password {{ matrix_password }}
          --device raspi
          --room-default {{ matrix_room }}
          --store {{ store_dir }}
        creates: "{{ config_dir }}/credentials.json"
        chdir: "{{ config_dir }}"
