- hosts: raspberry4
  roles:
    - ssh
    - storage
    - commandline
    - rclone
    - restic
    - syncthing
    - role: logging
      when:
        - use_logging is defined
        - use_logging|bool == true
