- hosts: raspberry4
  roles:
    - role: mikolak-net.raspi_config
      become: true
    - ssh
    - storage
    - commandline
    - rclone
    - restic
    - syncthing
    - name: backup
      tags: backup
    - role: matrix-commander
      when:
        - use_logging is defined
        - use_logging|bool == true
