- name: Configure ssh
  hosts: raspberry4
  tasks:
    - name: Enable PubkeyAuthentication
      block:
        - ansible.builtin.lineinfile:
            regexp: r"^\s*PubkeyAuthentication\s*yes"
            line: "PubkeyAuthentication yes"
            path: /etc/ssh/sshd_config
            state: present
            backup: true

        - ansible.builtin.lineinfile:
            regexp: r"^\s*PubkeyAuthentication\s*no"
            path: /etc/ssh/sshd_config
            state: absent
            backup: true
      become: true

    - name: Disable PasswordAuthentication
      block:
        - ansible.builtin.lineinfile:
            regexp: r"^\s*PasswordAuthentication\s*no"
            line: "PasswordAuthentication no"
            path: /etc/ssh/sshd_config
            state: present
            backup: true

        - ansible.builtin.lineinfile:
            regexp: r"^\s*PubkeyAuthentication\s*yes"
            path: /etc/ssh/sshd_config
            state: absent
            backup: true
      become: true
